#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )


clippy=$(xclip -o| sed 's/.*:\/\///' | sed 's/www\.//' | sed 's/\/.*//')
echo "$clippy"

input=$(printf '%s\n' "${password_files[@]}" | grep "$clippy")
if [ -z "$input" ]; then
	password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@" -p "unmatched: $clippy")
else
	if (( $(grep -c . <<<"$input") == 1 )); then
		password="$input"
	else
		password=$(printf '%s\n' "${input[@]}" | dmenu "$@" -p "$clippy")
	fi
fi

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
##	pass show -c "$password" 2>/dev/null
##	pass show -c "$password" 2>/dev/null | timeout 5 dmenu "$@"
	## pass does some weird fork stuff for -c, so i need head here or it gets stuck waiting for an EOF
	outpass=$(pass show -c "$password" 2>/dev/null | head -n 1)
##	echo "$outpass"
	##can replace this with xmessage or whatever pop up thing you want
	echo "$outpass" | timeout 5 dmenu "$@"
else
	xdotool - <<<"type --clearmodifiers -- $(pass show "$password" | head -n 1)"
fi
